module SurrealDB
  VERSION: String

  class Response
    attr_reader result: Array[Hash]
    attr_reader status: String
    attr_reader time: String

    def initialize: (Hash) -> void
    def success?: () -> bool
    def error?: () -> bool
  end
end
