name: Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'
    services:
      surrealdb:
        image: rinatshay/surrealdb-service:latest
        ports:
        - 8000:8000

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run lints
      run: bundle exec rubocop
    - name: Run tests
      env:
        DATABASE_URL: surrealdb://root:root@localhost:8000/test/test
      run: bundle exec rake test
